import './globals.css';
import { Bubbler_One } from 'next/font/google';

const bubbler = Bubbler_One({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

export const metadata = {
  title: {
    templete: '%s | BalkanaTry Web App',
    default: 'Welcome to BalkanaTry',
  },

  description: 'Web app about Balkana generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${bubbler.className} antialiased bg-primary-100 text-accent-300 font-normal min-h-screen flex flex-col relative`}
      >
        <div className='flex-1 px-8 py-12 grid'>
          <main className='max-w-7xl mx-auto w-full'>{children}</main>
        </div>
      </body>
    </html>
  );
}
